### ISSUE TITLE
How do we add additional search engines?

### ISSUE THREAD

**Issue by ctschach** [DanSnow/hoarder-pipette#47]
Interesting project and I love the idea....but....

as I'm located in Germany, I mainly use google.de for my searches. While the extension work for google.com, it does not for google.de. How can we add this domain into the supported sites. The same would apply to DuckDuckGo which I also often use.

Thanks for your support....

**Comment by DanSnow** [comment]
Hi @ctschach ,

Thanks for the issue! I'll add google.de support, but it might be a version or two away.  Since the extension is already on the Chrome Web Store, I can't just add new website permissions without potentially disabling it for current users. I'll probably do it like ublacklist (see: [https://github.com/iorate/ublacklist/pull/19](https://github.com/iorate/ublacklist/pull/19)) where you can enable extra site support in settings. This might take a bit longer, thanks for understanding!

**Comment by ridizy** [comment]
Thank you for this update.  However, it appears to have disabled Google for me.  When I'm on the google search page I only have:
![Image](https://github.com/user-attachments/assets/51c49c65-f1e5-48c5-86b5-02c88d7a8a32)

And here are my extension settings:
![Image](https://github.com/user-attachments/assets/33917a3b-4b30-4e3c-9dae-142bbd7a2202)


Separately, would it be possible to add duckduckgo.com?

**Comment by timthinks** [comment]
@ridizy I think it is a bug. When i click the arrow next to "ecosia" in your first screenshot, and then go back, i see the list of all the search engines and then i can click the icon to the left of google.

**Comment by ridizy** [comment]
Thanks @timthinks.  I can confirm the same behavior on my machine.

**Comment by DanSnow** [comment]
I've submitted a new version, and this issue should be fixed soon. Please let me know if you encounter any further problems.

**Comment by ridizy** [comment]
Will do.  Still showing 1.2.1 in the chrome web store.  I will test as soon as the new version is available.  Thank you!

**Comment by ridizy** [comment]
Strange, the web store is still not showing 1.2.2

**Comment by ridizy** [comment]
Thank you!  I updated to 1.2.2 and it resolved the display issue.
